name: PR Template
description: Pull request template.
title: "[PR]: "
labels: "pull request"
body:
- type: markdown
  attributes:
    value: |
      # Pull request template
- type: input
  id: parent_task
  attributes:
    label: Task being closed with PR
    description: "Enter the issue number of the task after the '#'."
    value: "Closes #"
  validations:
    required: true
- type: textarea
  id: task_description
  attributes:
    label: Description of pull request
    description: "Describe with a sentence or two the work you have completed."
  validations:
    required: true
- type: checkboxes
  id: completed-manual-steps
  attributes:
    label: Required Manual Steps
    description: "Confirm that these steps have been taken before new issue is created."
    options:
      - label: "Confirm title is filled out"
        required: true
      - label: "Definition of done is complete so far."
        required: true
      - label: "Confirm Task has correct issue id"
        required: true
      - label: "Confirm PR is going to dev and NOT main"
        required: true
