name: Task Template
description: Developer defined task.
title: "[Task]: "
labels: documentation
body:
- type: markdown
  attributes:
    value: |
      hey bro.
- type: dropdown
  id: labels
  attributes:
    label: This is my label.
    multiple: false
    options:
      - Option 1
      - Option 2
