name: Task Template
description: Developer defined task.
title: "[Task]: "
labels: documentation
body:
- type: markdown
  attributes:
    value: |
      # Welcome Message
- type: input
  id: parent_pbi
  attributes:
    label: Parent Backlog Item
    description: "..."
    placeholder: "#xx"
  validations:
    required: true
- type: textarea
  id: task_description
  attributes:
    label: Description of task
    description: "Describe with a sentence or two the task."
  validations:
    required: true
